INSERT INTO `base_country_info` VALUES (1, '101', 'AFG', '阿富汗', 'Afghanistan', NULL);
INSERT INTO `base_country_info` VALUES (2, '102', 'BHR', '巴林', 'Bahrian', NULL);
INSERT INTO `base_country_info` VALUES (3, '103', 'BGD', '孟加拉国', 'Bangladesh', NULL);
INSERT INTO `base_country_info` VALUES (4, '104', 'BTN', '不丹', 'Bhutan', NULL);
INSERT INTO `base_country_info` VALUES (5, '105', 'BRN', '文莱', 'Brunei', NULL);
INSERT INTO `base_country_info` VALUES (6, '106', 'MMR', '缅甸', 'Myanmar', NULL);
INSERT INTO `base_country_info` VALUES (7, '107', 'KHM', '柬埔寨', 'Cambodia', NULL);
INSERT INTO `base_country_info` VALUES (8, '108', 'CYP', '塞浦路斯', 'Cyprus', NULL);
INSERT INTO `base_country_info` VALUES (9, '109', 'PRK', '朝鲜', 'Korea,DPR', NULL);
INSERT INTO `base_country_info` VALUES (10, '110', 'HKG', '香港', 'Hong Kong', NULL);
INSERT INTO `base_country_info` VALUES (11, '111', 'IND', '印度', 'India', NULL);
INSERT INTO `base_country_info` VALUES (12, '112', 'IDN', '印度尼西亚', 'Indonesia', NULL);
INSERT INTO `base_country_info` VALUES (13, '113', 'IRN', '伊朗', 'Iran', NULL);
INSERT INTO `base_country_info` VALUES (14, '114', 'IRQ', '伊拉克', 'Iraq', NULL);
INSERT INTO `base_country_info` VALUES (15, '115', 'ISR', '以色列', 'Israel', NULL);
INSERT INTO `base_country_info` VALUES (16, '116', 'JPN', '日本', 'Japan', NULL);
INSERT INTO `base_country_info` VALUES (17, '117', 'JOR', '约旦', 'Jordan', NULL);
INSERT INTO `base_country_info` VALUES (18, '118', 'KWT', '科威特', 'Kuwait', NULL);
INSERT INTO `base_country_info` VALUES (19, '119', 'LAO', '老挝', 'Lao PDR', NULL);
INSERT INTO `base_country_info` VALUES (20, '120', 'LBN', '黎巴嫩', 'Lebanon', NULL);
INSERT INTO `base_country_info` VALUES (21, '121', 'MAC', '澳门', 'Macau', NULL);
INSERT INTO `base_country_info` VALUES (22, '122', 'MYS', '马来西亚', 'Malaysia', NULL);
INSERT INTO `base_country_info` VALUES (23, '123', 'MDV', '马尔代夫', 'Maldives', NULL);
INSERT INTO `base_country_info` VALUES (24, '124', 'MNG', '蒙古', 'Mongolia', NULL);
INSERT INTO `base_country_info` VALUES (25, '125', 'NPL', '尼泊尔联邦民主共和国', 'Nepal, FDR', NULL);
INSERT INTO `base_country_info` VALUES (26, '126', 'OMN', '阿曼', 'Oman', NULL);
INSERT INTO `base_country_info` VALUES (27, '127', 'PAK', '巴基斯坦', 'Pakistan', NULL);
INSERT INTO `base_country_info` VALUES (28, '128', 'PSE', '巴勒斯坦', 'Palestine', NULL);
INSERT INTO `base_country_info` VALUES (29, '129', 'PHL', '菲律宾', 'Philippines', NULL);
INSERT INTO `base_country_info` VALUES (30, '130', 'QAT', '卡塔尔', 'Qatar', NULL);
INSERT INTO `base_country_info` VALUES (31, '131', 'SAU', '沙特阿拉伯', 'Saudi Arabia', NULL);
INSERT INTO `base_country_info` VALUES (32, '132', 'SGP', '新加坡', 'Singapore', NULL);
INSERT INTO `base_country_info` VALUES (33, '133', 'KOR', '韩国', 'Korea, Rep.', NULL);
INSERT INTO `base_country_info` VALUES (34, '134', 'LKA', '斯里兰卡', 'Sri Lanka', NULL);
INSERT INTO `base_country_info` VALUES (35, '135', 'SYR', '叙利亚', 'Syrian Arab Republic', NULL);
INSERT INTO `base_country_info` VALUES (36, '136', 'THA', '泰国', 'Thailand', NULL);
INSERT INTO `base_country_info` VALUES (37, '137', 'TUR', '土耳其', 'Turkey', NULL);
INSERT INTO `base_country_info` VALUES (38, '138', 'ARE', '阿联酋', 'United Arab Emirates', NULL);
INSERT INTO `base_country_info` VALUES (39, '139', 'YEM', '也门', 'Yemen', NULL);
INSERT INTO `base_country_info` VALUES (40, '141', 'NVM', '越南', 'Viet Nam', NULL);
INSERT INTO `base_country_info` VALUES (41, '142', 'CHN', '中国', 'China', NULL);
INSERT INTO `base_country_info` VALUES (42, '143', 'TWN', '台澎金马关税区', 'Taiwan, Prov.of China', NULL);
INSERT INTO `base_country_info` VALUES (43, '144', 'TLS', '东帝汶', 'Timor-Leste', NULL);
INSERT INTO `base_country_info` VALUES (44, '145', 'KAZ', '哈萨克斯坦', 'Kazakhstan', NULL);
INSERT INTO `base_country_info` VALUES (45, '146', 'KGZ', '吉尔吉斯斯坦', 'Kyrgyzstan', NULL);
INSERT INTO `base_country_info` VALUES (46, '147', 'TJK', '塔吉克斯坦', 'Tajikistan', NULL);
INSERT INTO `base_country_info` VALUES (47, '148', 'TKM', '土库曼斯坦', 'Turkmenistan', NULL);
INSERT INTO `base_country_info` VALUES (48, '149', 'UZB', '乌兹别克斯坦', 'Uzbekistan', NULL);
INSERT INTO `base_country_info` VALUES (49, '199', '', '亚洲其他国家(地区)', 'Oth. Asia nes', NULL);
INSERT INTO `base_country_info` VALUES (50, '201', 'DZA', '阿尔及利亚', 'Algeria', NULL);
INSERT INTO `base_country_info` VALUES (51, '202', 'AGO', '安哥拉', 'Angola', NULL);
INSERT INTO `base_country_info` VALUES (52, '203', 'BEN', '贝宁', 'Benin', NULL);
INSERT INTO `base_country_info` VALUES (53, '204', 'BWA', '博茨瓦纳', 'Botswana', NULL);
INSERT INTO `base_country_info` VALUES (54, '205', 'BDI', '布隆迪', 'Burundi', NULL);
INSERT INTO `base_country_info` VALUES (55, '206', 'CMR', '喀麦隆', 'Cameroon', NULL);
INSERT INTO `base_country_info` VALUES (56, '207', '', '加那利群岛', 'Canary Islands', NULL);
INSERT INTO `base_country_info` VALUES (57, '208', 'CPV', '佛得角', 'Cape Verde', NULL);
INSERT INTO `base_country_info` VALUES (58, '209', 'CAF', '中非', 'Central African Republic.', NULL);
INSERT INTO `base_country_info` VALUES (59, '210', '', '塞卜泰(休达)', 'Ceuta', NULL);
INSERT INTO `base_country_info` VALUES (60, '211', 'TCD', '乍得', 'Chad', NULL);
INSERT INTO `base_country_info` VALUES (61, '212', 'COM', '科摩罗', 'Comoros', NULL);
INSERT INTO `base_country_info` VALUES (62, '213', 'COG', '刚果(布)', 'Congo', NULL);
INSERT INTO `base_country_info` VALUES (63, '214', 'DJI', '吉布提', 'Djibouti', NULL);
INSERT INTO `base_country_info` VALUES (64, '215', 'EGY', '埃及', 'Egypt', NULL);
INSERT INTO `base_country_info` VALUES (65, '216', 'GNQ', '赤道几内亚', 'Equatorial Guinea', NULL);
INSERT INTO `base_country_info` VALUES (66, '217', 'ETH', '埃塞俄比亚', 'Ethiopia', NULL);
INSERT INTO `base_country_info` VALUES (67, '218', 'GAB', '加蓬', 'Gabon', NULL);
INSERT INTO `base_country_info` VALUES (68, '219', 'GMB', '冈比亚', 'Gambia', NULL);
INSERT INTO `base_country_info` VALUES (69, '220', 'GHA', '加纳', 'Ghana', NULL);
INSERT INTO `base_country_info` VALUES (70, '221', 'GIN', '几内亚', 'Guinea', NULL);
INSERT INTO `base_country_info` VALUES (71, '222', 'GNB', '几内亚比绍', 'Guinea-Bissau', NULL);
INSERT INTO `base_country_info` VALUES (72, '223', 'CIV', '科特迪瓦', "Cote d'lvoire", NULL);
INSERT INTO `base_country_info` VALUES (73, '224', 'KEN', '肯尼亚', 'Kenya', NULL);
INSERT INTO `base_country_info` VALUES (74, '225', 'LBR', '利比里亚', 'Liberia', NULL);
INSERT INTO `base_country_info` VALUES (75, '226', 'LBY', '利比亚', 'Libyan Arab Jamahiriya', NULL);
INSERT INTO `base_country_info` VALUES (76, '227', 'MDG', '马达加斯加', 'Madagascar', NULL);
INSERT INTO `base_country_info` VALUES (77, '228', 'MWI', '马拉维', 'Malawi', NULL);
INSERT INTO `base_country_info` VALUES (78, '229', 'MLI', '马里', 'Mali', NULL);
INSERT INTO `base_country_info` VALUES (79, '230', 'MRT', '毛里塔尼亚', 'Mauritania', NULL);
INSERT INTO `base_country_info` VALUES (80, '231', 'MUS', '毛里求斯', 'Mauritius', NULL);
INSERT INTO `base_country_info` VALUES (81, '232', 'MAR', '摩洛哥', 'Morocco', NULL);
INSERT INTO `base_country_info` VALUES (82, '233', 'MOZ', '莫桑比克', 'Mozambique', NULL);
INSERT INTO `base_country_info` VALUES (83, '234', 'NAM', '纳米比亚', 'Namibia', NULL);
INSERT INTO `base_country_info` VALUES (84, '235', 'NER', '尼日尔', 'Niger', NULL);
INSERT INTO `base_country_info` VALUES (85, '236', 'NGA', '尼日利亚', 'Nigeria', NULL);
INSERT INTO `base_country_info` VALUES (86, '237', 'REU', '留尼汪', 'Reunion', NULL);
INSERT INTO `base_country_info` VALUES (87, '238', 'RWA', '卢旺达', 'Rwanda', NULL);
INSERT INTO `base_country_info` VALUES (88, '239', 'STP', '圣多美和普林西比', 'Sao Tome and Principe', NULL);
INSERT INTO `base_country_info` VALUES (89, '240', 'SEN', '塞内加尔', 'Senegal', NULL);
INSERT INTO `base_country_info` VALUES (90, '241', 'SYC', '塞舌尔', 'Seychelles', NULL);
INSERT INTO `base_country_info` VALUES (91, '242', 'SLE', '塞拉利昂', 'Sierra Leone', NULL);
INSERT INTO `base_country_info` VALUES (92, '243', 'SOM', '索马里', 'Somalia', NULL);
INSERT INTO `base_country_info` VALUES (93, '244', 'ZAF', '南非', 'South Africa', NULL);
INSERT INTO `base_country_info` VALUES (94, '245', 'ESH', '西撒哈拉', 'Western Sahara', NULL);
INSERT INTO `base_country_info` VALUES (95, '246', 'SDN', '苏丹', 'Sudan', NULL);
INSERT INTO `base_country_info` VALUES (96, '247', 'TZA', '坦桑尼亚', 'Tanzania', NULL);
INSERT INTO `base_country_info` VALUES (97, '248', 'TGO', '多哥', 'Togo', NULL);
INSERT INTO `base_country_info` VALUES (98, '249', 'TUN', '突尼斯', 'Tunisia', NULL);
INSERT INTO `base_country_info` VALUES (99, '250', 'UGA', '乌干达', 'Uganda', NULL);
INSERT INTO `base_country_info` VALUES (100, '251', 'BFA', '布基纳法索', 'Burkina Faso', NULL);
INSERT INTO `base_country_info` VALUES (101, '252', 'COD', '刚果(金)', 'Congo,DR', NULL);
INSERT INTO `base_country_info` VALUES (102, '253', 'ZMB', '赞比亚', 'Zambia', NULL);
INSERT INTO `base_country_info` VALUES (103, '254', 'ZWE', '津巴布韦', 'Zimbabwe', NULL);
INSERT INTO `base_country_info` VALUES (104, '255', 'LSO', '莱索托', 'Lesotho', NULL);
INSERT INTO `base_country_info` VALUES (105, '256', '', '梅利利亚', 'Melilla', NULL);
INSERT INTO `base_country_info` VALUES (106, '257', 'SWZ', '斯威士兰', 'Swaziland', NULL);
INSERT INTO `base_country_info` VALUES (107, '258', 'ERI', '厄立特里亚', 'Eritrea', NULL);
INSERT INTO `base_country_info` VALUES (108, '259', 'MYT', '马约特', 'Mayotte', NULL);
INSERT INTO `base_country_info` VALUES (109, '260', 'NULL', '南苏丹共和国', 'Republic of South Sudan ', NULL);
INSERT INTO `base_country_info` VALUES (110, '299', '', '非洲其他国家(地区)', 'Oth. Afr. nes', NULL);
INSERT INTO `base_country_info` VALUES (111, '301', 'BEL', '比利时', 'Belgium', NULL);
INSERT INTO `base_country_info` VALUES (112, '302', 'DNK', '丹麦', 'Denmark', NULL);
INSERT INTO `base_country_info` VALUES (113, '303', 'GBR', '英国', 'United Kingdom', NULL);
INSERT INTO `base_country_info` VALUES (114, '304', 'DEU', '德国', 'Germany', NULL);
INSERT INTO `base_country_info` VALUES (115, '305', 'FRA', '法国', 'France', NULL);
INSERT INTO `base_country_info` VALUES (116, '306', 'IRL', '爱尔兰', 'Ireland', NULL);
INSERT INTO `base_country_info` VALUES (117, '307', 'ITA', '意大利', 'Italy', NULL);
INSERT INTO `base_country_info` VALUES (118, '308', 'LUX', '卢森堡', 'Luxembourg', NULL);
INSERT INTO `base_country_info` VALUES (119, '309', 'NLD', '荷兰', 'Netherlands', NULL);
INSERT INTO `base_country_info` VALUES (120, '310', 'GRC', '希腊', 'Greece', NULL);
INSERT INTO `base_country_info` VALUES (121, '311', 'PRT', '葡萄牙', 'Portugal', NULL);
INSERT INTO `base_country_info` VALUES (122, '312', 'ESP', '西班牙', 'Spain', NULL);
INSERT INTO `base_country_info` VALUES (123, '313', 'ALB', '阿尔巴尼亚', 'Albania', NULL);
INSERT INTO `base_country_info` VALUES (124, '314', 'AND', '安道尔', 'Andorra', NULL);
INSERT INTO `base_country_info` VALUES (125, '315', 'AUT', '奥地利', 'Austria', NULL);
INSERT INTO `base_country_info` VALUES (126, '316', 'BGR', '保加利亚', 'Bulgaria', NULL);
INSERT INTO `base_country_info` VALUES (127, '318', 'FIN', '芬兰', 'Finland', NULL);
INSERT INTO `base_country_info` VALUES (128, '320', 'GIB', '直布罗陀', 'Gibraltar', NULL);
INSERT INTO `base_country_info` VALUES (129, '321', 'HUN', '匈牙利', 'Hungary', NULL);
INSERT INTO `base_country_info` VALUES (130, '322', 'ISL', '冰岛', 'Iceland', NULL);
INSERT INTO `base_country_info` VALUES (131, '323', 'LIE', '列支敦士登', 'Liechtenstein', NULL);
INSERT INTO `base_country_info` VALUES (132, '324', 'MLT', '马耳他', 'Malta', NULL);
INSERT INTO `base_country_info` VALUES (133, '325', 'MCO', '摩纳哥', 'Monaco', NULL);
INSERT INTO `base_country_info` VALUES (134, '326', 'NOR', '挪威', 'Norway', NULL);
INSERT INTO `base_country_info` VALUES (135, '327', 'POL', '波兰', 'Poland', NULL);
INSERT INTO `base_country_info` VALUES (136, '328', 'ROM', '罗马尼亚', 'Romania', NULL);
INSERT INTO `base_country_info` VALUES (137, '329', 'SMR', '圣马力诺', 'San Marino', NULL);
INSERT INTO `base_country_info` VALUES (138, '330', 'SWE', '瑞典', 'Sweden', NULL);
INSERT INTO `base_country_info` VALUES (139, '331', 'CHE', '瑞士', 'Switzerland', NULL);
INSERT INTO `base_country_info` VALUES (140, '334', 'EST', '爱沙尼亚', 'Estonia', NULL);
INSERT INTO `base_country_info` VALUES (141, '335', 'LVA', '拉脱维亚', 'Latvia', NULL);
INSERT INTO `base_country_info` VALUES (142, '336', 'LTU', '立陶宛', 'Lithuania', NULL);
INSERT INTO `base_country_info` VALUES (143, '337', 'GEO', '格鲁吉亚', 'Georgia', NULL);
INSERT INTO `base_country_info` VALUES (144, '338', 'ARM', '亚美尼亚', 'Armenia', NULL);
INSERT INTO `base_country_info` VALUES (145, '339', 'AZE', '阿塞拜疆', 'Azerbai jan', NULL);
INSERT INTO `base_country_info` VALUES (146, '340', 'BLR', '白俄罗斯', 'Belarus', NULL);
INSERT INTO `base_country_info` VALUES (147, '343', 'MDA', '摩尔多瓦', 'Moldova', NULL);
INSERT INTO `base_country_info` VALUES (148, '344', 'RUS', '俄罗斯联邦', 'Russian Federation', NULL);
INSERT INTO `base_country_info` VALUES (149, '347', 'UKR', '乌克兰', 'Ukraine', NULL);
INSERT INTO `base_country_info` VALUES (150, '349', 'NULL', '塞尔维亚和黑山', '', NULL);
INSERT INTO `base_country_info` VALUES (151, '350', 'SVN', '斯洛文尼亚', 'Slovenia ', NULL);
INSERT INTO `base_country_info` VALUES (152, '351', 'HRV', '克罗地亚', 'Croatia', NULL);
INSERT INTO `base_country_info` VALUES (153, '352', 'CZE', '捷克', 'Czech Republic', NULL);
INSERT INTO `base_country_info` VALUES (154, '353', 'SVK', '斯洛伐克', 'Slovakia', NULL);
INSERT INTO `base_country_info` VALUES (155, '354', 'MKD', '前南马其顿', 'Macedonia,FYR', NULL);
INSERT INTO `base_country_info` VALUES (156, '355', 'BIH', '波黑', 'Bosnia and Hercegovina', NULL);
INSERT INTO `base_country_info` VALUES (157, '356', 'VAT', '梵蒂冈城国', 'Vatican City State', NULL);
INSERT INTO `base_country_info` VALUES (158, '357', 'FRO', '法罗群岛', 'Faroe Islands', NULL);
INSERT INTO `base_country_info` VALUES (159, '358', 'SRB', '塞尔维亚', 'Serbia', NULL);
INSERT INTO `base_country_info` VALUES (160, '359', 'MNE', '黑山', 'Montenegro', NULL);
INSERT INTO `base_country_info` VALUES (161, '399', '', '欧洲其他国家(地区)', 'Oth. Eur. nes', NULL);
INSERT INTO `base_country_info` VALUES (162, '401', 'ATG', '安提瓜和巴布达', 'Antigua & Barbuda', NULL);
INSERT INTO `base_country_info` VALUES (163, '402', 'ARG', '阿根廷', 'Argentina', NULL);
INSERT INTO `base_country_info` VALUES (164, '403', 'ABW', '阿鲁巴', 'Aruba', NULL);
INSERT INTO `base_country_info` VALUES (165, '404', 'BHS', '巴哈马', 'Bahamas', NULL);
INSERT INTO `base_country_info` VALUES (166, '405', 'BRB', '巴巴多斯', 'Barbados', NULL);
INSERT INTO `base_country_info` VALUES (167, '406', 'BLZ', '伯利兹', 'Belize', NULL);
INSERT INTO `base_country_info` VALUES (168, '408', 'BOL', '多民族玻利维亚国', 'Estado Plurinacional de Bolivia', NULL);
INSERT INTO `base_country_info` VALUES (169, '409', '', '博内尔', 'Bonaire', NULL);
INSERT INTO `base_country_info` VALUES (170, '410', 'BRA', '巴西', 'Brazil', NULL);
INSERT INTO `base_country_info` VALUES (171, '411', 'CYM', '开曼群岛', 'Cayman Islands', NULL);
INSERT INTO `base_country_info` VALUES (172, '412', 'CHL', '智利', 'Chile', NULL);
INSERT INTO `base_country_info` VALUES (173, '413', 'COL', '哥伦比亚', 'Colombia', NULL);
INSERT INTO `base_country_info` VALUES (174, '414', 'DMA', '多米尼克', 'Dominica', NULL);
INSERT INTO `base_country_info` VALUES (175, '415', 'CRI', '哥斯达黎加', 'Costa Rica', NULL);
INSERT INTO `base_country_info` VALUES (176, '416', 'CUB', '古巴', 'Cuba', NULL);
INSERT INTO `base_country_info` VALUES (177, '417', '', '库腊索岛', 'Curacao', NULL);
INSERT INTO `base_country_info` VALUES (178, '418', 'DOM', '多米尼加共和国', 'Dominican Republic', NULL);
INSERT INTO `base_country_info` VALUES (179, '419', 'ECU', '厄瓜多尔', 'Ecuador', NULL);
INSERT INTO `base_country_info` VALUES (180, '420', 'GUF', '法属圭亚那', 'French Guiana', NULL);
INSERT INTO `base_country_info` VALUES (181, '421', 'GRD', '格林纳达', 'Grenada', NULL);
INSERT INTO `base_country_info` VALUES (182, '422', 'GLP', '瓜德罗普', 'Guadeloupe', NULL);
INSERT INTO `base_country_info` VALUES (183, '423', 'GTM', '危地马拉', 'Guatemala', NULL);
INSERT INTO `base_country_info` VALUES (184, '424', 'GUY', '圭亚那', 'Guyana', NULL);
INSERT INTO `base_country_info` VALUES (185, '425', 'HTI', '海地', 'Haiti', NULL);
INSERT INTO `base_country_info` VALUES (186, '426', 'HND', '洪都拉斯', 'Honduras', NULL);
INSERT INTO `base_country_info` VALUES (187, '427', 'JAM', '牙买加', 'Jamaica', NULL);
INSERT INTO `base_country_info` VALUES (188, '428', 'MTQ', '马提尼克', 'Martinique', NULL);
INSERT INTO `base_country_info` VALUES (189, '429', 'MEX', '墨西哥', 'Mexico', NULL);
INSERT INTO `base_country_info` VALUES (190, '430', 'MSR', '蒙特塞拉特', 'Montserrat', NULL);
INSERT INTO `base_country_info` VALUES (191, '431', 'NIC', '尼加拉瓜', 'Nicaragua', NULL);
INSERT INTO `base_country_info` VALUES (192, '432', 'PAN', '巴拿马', 'Panama', NULL);
INSERT INTO `base_country_info` VALUES (193, '433', 'PRY', '巴拉圭', 'Paraguay', NULL);
INSERT INTO `base_country_info` VALUES (194, '434', 'PER', '秘鲁', 'Peru', NULL);
INSERT INTO `base_country_info` VALUES (195, '435', 'PRI', '波多黎各', 'Puerto Rico', NULL);
INSERT INTO `base_country_info` VALUES (196, '436', '', '萨巴', 'Saba', NULL);
INSERT INTO `base_country_info` VALUES (197, '437', 'LCA', '圣卢西亚', 'Saint Lucia', NULL);
INSERT INTO `base_country_info` VALUES (198, '438', '', '圣马丁岛', 'Saint Martin Islands', NULL);
INSERT INTO `base_country_info` VALUES (199, '439', 'VCT', '圣文森特和格林纳丁斯', 'Saint Vincent and Grenadines', NULL);
INSERT INTO `base_country_info` VALUES (200, '440', 'SLV', '萨尔瓦多', 'El Salvador', NULL);
INSERT INTO `base_country_info` VALUES (201, '441', 'SUR', '苏里南', 'Suriname', NULL);
INSERT INTO `base_country_info` VALUES (202, '442', 'TTO', '特立尼达和多巴哥', 'Trinidad and Tobago', NULL);
INSERT INTO `base_country_info` VALUES (203, '443', 'TCA', '特克斯和凯科斯群岛', 'Turks and Caicos Islands', NULL);
INSERT INTO `base_country_info` VALUES (204, '444', 'URY', '乌拉圭', 'Uruguay', NULL);
INSERT INTO `base_country_info` VALUES (205, '445', 'VEN', '委内瑞拉', 'Venezuela', NULL);
INSERT INTO `base_country_info` VALUES (206, '446', 'VGB', '英属维尔京群岛', 'Virgin  Islands, British', NULL);
INSERT INTO `base_country_info` VALUES (207, '447', 'KNA', '圣其茨和尼维斯', 'Saint  Kitts and Nevis', NULL);
INSERT INTO `base_country_info` VALUES (208, '448', 'SPM', '圣皮埃尔和密克隆', 'Saint.Pierre and Miquelon', NULL);
INSERT INTO `base_country_info` VALUES (209, '449', 'ANT', '荷属安地列斯', 'Netherlands Antilles', NULL);
INSERT INTO `base_country_info` VALUES (210, '499', '', '拉丁美洲其他国家(地区)', 'Oth. L.Amer. nes', NULL);
INSERT INTO `base_country_info` VALUES (211, '501', 'CAN', '加拿大', 'Canada', NULL);
INSERT INTO `base_country_info` VALUES (212, '502', 'USA', '美国', 'United States', NULL);
INSERT INTO `base_country_info` VALUES (213, '503', 'GRL', '格陵兰', 'Greenland', NULL);
INSERT INTO `base_country_info` VALUES (214, '504', 'BMU', '百慕大', 'Bermuda', NULL);
INSERT INTO `base_country_info` VALUES (215, '599', '', '北美洲其他国家(地区)', 'Oth. N.Amer. nes', NULL);
INSERT INTO `base_country_info` VALUES (216, '601', 'AUS', '澳大利亚', 'Australia', NULL);
INSERT INTO `base_country_info` VALUES (217, '602', 'COK', '库克群岛', 'Cook Islands', NULL);
INSERT INTO `base_country_info` VALUES (218, '603', 'FJI', '斐济', 'Fiji', NULL);
INSERT INTO `base_country_info` VALUES (219, '604', '', '盖比群岛', 'Gambier Islands', NULL);
INSERT INTO `base_country_info` VALUES (220, '605', '', '马克萨斯群岛', 'Marquesas Islands', NULL);
INSERT INTO `base_country_info` VALUES (221, '606', 'NRU', '瑙鲁', 'Nauru', NULL);
INSERT INTO `base_country_info` VALUES (222, '607', 'NCL', '新喀里多尼亚', 'New Caledonia', NULL);
INSERT INTO `base_country_info` VALUES (223, '608', 'VUT', '瓦努阿图', 'Vanuatu', NULL);
INSERT INTO `base_country_info` VALUES (224, '609', 'NZL', '新西兰', 'New Zealand', NULL);
INSERT INTO `base_country_info` VALUES (225, '610', 'NFK', '诺福克岛', 'Norfolk Island', NULL);
INSERT INTO `base_country_info` VALUES (226, '611', 'PNG', '巴布亚新几内亚', 'Papua New Guinea', NULL);
INSERT INTO `base_country_info` VALUES (227, '612', '', '社会群岛', 'Society Islands', NULL);
INSERT INTO `base_country_info` VALUES (228, '613', 'SLB', '所罗门群岛', 'Solomon Islands', NULL);
INSERT INTO `base_country_info` VALUES (229, '614', 'TON', '汤加', 'Tonga', NULL);
INSERT INTO `base_country_info` VALUES (230, '615', '', '土阿莫土群岛', 'Tuamotu Islands', NULL);
INSERT INTO `base_country_info` VALUES (231, '616', '', '土布艾群岛', 'Tubai Islands', NULL);
INSERT INTO `base_country_info` VALUES (232, '617', 'WSM', '萨摩亚', 'Samoa', NULL);
INSERT INTO `base_country_info` VALUES (233, '618', 'KIR', '基里巴斯', 'Kiribati', NULL);
INSERT INTO `base_country_info` VALUES (234, '619', 'TUV', '图瓦卢', 'Tuvalu', NULL);
INSERT INTO `base_country_info` VALUES (235, '620', 'FSM', '密克罗尼西亚联邦', 'Micronesia, Fs', NULL);
INSERT INTO `base_country_info` VALUES (236, '621', 'MHL', '马绍尔群岛', 'Marshall Islands', NULL);
INSERT INTO `base_country_info` VALUES (237, '622', 'PLW', '帕劳', 'Palau', NULL);
INSERT INTO `base_country_info` VALUES (238, '623', 'PYF', '法属波利尼西亚', 'French Polynesia', NULL);
INSERT INTO `base_country_info` VALUES (239, '625', 'WLF', '瓦利斯和浮图纳', 'Wallis and Futuna', NULL);
INSERT INTO `base_country_info` VALUES (240, '699', '', '大洋洲其他国家(地区)', 'Oth. Ocean. nes', NULL);
INSERT INTO `base_country_info` VALUES (241, '701', '', '国(地)别不详', 'Countries(reg.) unknown', NULL);
INSERT INTO `base_country_info` VALUES (242, '702', '', '联合国及机构和国际组织', "UN and oth. int\'l  org.", NULL);
INSERT INTO `base_country_info` VALUES (243, '999', '', '中性包装原产国别', 'Conutries of Neutral Package', NULL);
